### ISSUE TITLE
Fix caching issue

### ISSUE THREAD

**Issue by alireza-ahmadi** [agallio/agallio.xyz#5]
I saw your [tweet](https://twitter.com/agalliosamai/status/1474744251556634626) and decided to find out the problem with your website's cache.

**_First_**, you haven't used the `headers` function in your `index.jsx` and `$slug.jsx`; As a result:

- If a user directly hits your home page, Vercel won't serve the cache because it doesn't know what should be cached.
- If a user directly hits a blog post, again, Vercel won't serve from the cache. If the user clicks on the logo and goes to the home page, Vercel will try to load from the cache.

TL;DR: If you don't provide `headers` function, the provided headers in the loader function will only be used on client-side navigation and not on the server-side navigation (aka your first load).

Learn more about header function [here](https://remix.run/docs/en/v1/api/conventions#headers). _Keep in mind that according to https://github.com/remix-run/remix/issues/1140 and my tests, `localHeaders` may not work, and you may have to manually duplicate the `Cache-Control` value in the headers function._

**_Second_**, Vercel doesn't understand the `max-age=N, stale-while-revalidate=M` format. You should also use the appropriate directive `max-age=N, public, stale-while-revalidate=M`.

**Your website's cache should work as expected by doing these two changes.** However, I have a few suggestions:

- Make sure to read the [Vercel caching guide](https://vercel.com/docs/concepts/edge-network/caching)
- Ideally, instead of setting `max-age`, you'd want to set `s-maxage` ([why?](https://stackoverflow.com/questions/39992837/s-maxage-and-maxage-difference)) so the browser always send the request to the server but, the server returns the cached response if it's available. (_Keep in mind that providing a directive like `public` is not required with `s-maxage`_)
- Again ideally, you'd want to set `s-maxage` to a value lower than `stale-while-revalidate`. This would allow the Vercel to always (until `stale-while-revalidate` seconds) try to return the cache but, try to renew the cache from time to time (after `s-maxage` seconds passed from the last renewal) in the background.

**Comment by agallio** [comment]
Thank you very much for the help! I tried to add the cache-control to the Remix headers function. Hopefully, it'll work! Fingers crossed 😅

**Comment by agallio** [comment]
It is now working perfectly. Thank you @alireza-ahmadi for your kind help! 🙇🏻
